### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by SCStudioSummer** [premnirmal/Magnet#15]
Dear Premnirmal,
I've applied Magnet in my free app (SC Memo),
thanks for your kindness to share this excellent open source!
Recently, some app users (most of them are using Android 6.0 devices) have reported the NullPointerException below:

java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at com.premnirmal.Magnet.Magnet.move(Magnet.java:318)
	at com.premnirmal.Magnet.Magnet$MoveAnimator.run(Magnet.java:380)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:168)
	at android.app.ActivityThread.main(ActivityThread.java:5885)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)

The onMove code in my project is:

//to remember the position
@Override
                        public void onMove(float x, float y) {
                            posX = (int) x;
                            posY = (int) y;
                        }

After days of works (googling and trying to modify my code...), I still cannot figure out the proper solution yet.
Could you please tell me that is there something I can do to fix this error in my code?
Thank you so much. = )

Best,
Summer

**Comment by premnirmal** [comment]
How did you initialize the magnet? In a service or in an activity? Looks like the context registered with the magnet is null so either your service or activity is destroyed

**Comment by SCStudioSummer** [comment]
My magnet are started in a service, below is the code of onStartComment(): 

@Override
    public int onStartCommand(final Intent intent, final int flags, final int startId) {

        //check the permission
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M){
            if (!Settings.canDrawOverlays(getApplicationContext())){
                stopSelf();
            }
        }

        //load data and build the magnet
        if (magnet == null){
            magnet = new Magnet.Builder(getApplicationContext())
                    .setIconView(generateTextView(reminder.getPicUri(), reminder.getTextColor(), reminder.getMemoColor(), reminder.getTextSize(), reminder.getMemo(), memoCount))
                    .setIconCallback(new IconCallback() {
                        @Override
                        public void onFlingAway() {
                            posX = width / 2;
                            posY = 0 - (height / 2) + 200;
                            savePosition();
                            stopSelf();
                        }

                        @Override
                        public void onMove(float x, float y) {
                            posX = (int) x;
                            posY = (int) y;
                        }

                        @Override
                        public void onIconClick(View view, float clickX, float clickY) {

                            savePosition();
                            removeMagnets();

                            //open another activity
                            final Intent dialogIntent = new Intent(MyService.this, HomeDialogActivity.class);
                            dialogIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                            startActivity(dialogIntent);
                            stopSelf();
                        }

                        @Override
                        public void onIconDestroyed() {}
                    })
                    .setInitialPosition(posX, posY)
                    .setRemoveIconResId(0x00000000)
                    .setRemoveIconShadow(0x00000000)
                    .setShouldStickToWall(false)
                    .build();
            magnet.show();
        }

        //a scheduledFuture to check if it's home screen or not every 2 seconds

        return super.onStartCommand(intent, flags, startId);
    }

this service is started when users leave my app's activities, or unlock the screen, 
here's the service's onDestroy():

@Override
    public void onDestroy() {
        if (magnet != null){
            magnet.destroy();
            magnet = null;
        }

        scheduledFuture.cancel(true);
    }

is there something i could do to prevent the exception, when (or before) the service being destroyed?
Thanks for your kindness to read and answer my dumb question... Thank you very much.

Best,
Summer

**Comment by premnirmal** [comment]
Try passing it the the service context instead of the application context, also be sure to destroy the magnet inside `onDestroy()` and also the `onTaskRemoved(Intent)` methods of your service to be sure that there are no null references to context inside the `Magnet` class

**Comment by SCStudioSummer** [comment]
Thanks for your help very much! Your instruction brings many insights for me. Really appreciate your kindness, thank you = )

**Comment by premnirmal** [comment]
Anytime. Let me know if you have any questions and please close the issue if resolved.

**Comment by SCStudioSummer** [comment]
Yes, this problem has been solved since I set the right context and destroyed the magnet properly. Thank you very much!! =D
