### ISSUE TITLE
[Compilation Error] Unresolved reference: newBuilder

### ISSUE THREAD

**Issue by tagantroy** [premnirmal/Magnet#18]
`BubbleService.kt: (56, 24): Unresolved reference: newBuilder`
we are use 'com.premnirmal.magnet:library:1.1.6'
previously this issue was fixed with --refresh-dependencies,but now it doesn't help

**Comment by premnirmal** [comment]
Hi @tagantroy 

Can you post the code for where you're initializing the magnet? It should be something like the demo app here: https://github.com/premnirmal/Magnet/blob/master/demo/src/main/java/com/premnirmal/Magnet/app/MyService.java#L29

**Comment by jason1peng** [comment]
Is that because 1.1.6 don't have this method?
Looks like newBuilder is add in commit 8492863300232fb44c179f3fb3d399f1219dcc49
But this commit is after 1.1.6 release.

**Comment by premnirmal** [comment]
Updated, please use **version 1.1.7**
