### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by AlaaZarifa** [premnirmal/Magnet#19]
I made a project just like the demo, and it didn't work and no bubble showed after giving the permission.!
so I cloned the library and run the demo module, and it worked the first time, if I open it again, no bubble showed just like my project..!?

Can you please double check the demo again, and see if you can add a button that shows the bubble.. and if pressed again it would delete the previous one and show a new one!?

**Comment by premnirmal** [comment]
Hi @AlaaZarifa - updated the demo app - try now
