### ISSUE TITLE
Attempting to destroy the window while drawing!

### ISSUE THREAD

**Issue by npes87184** [premnirmal/Magnet#21]
Hi,

When the onIconDestroyed is called, it will show this message and nothing happens.

E/ViewRootImpl[]: Attempting to destroy the window while drawing!
                           window=android.view.ViewRootImpl@aa5238c, title=

Thanks.

**Comment by premnirmal** [comment]
Hi @npes87184 , can you give me more context. What is the issue? What are you trying to do?

**Comment by npes87184** [comment]
Hi, @premnirmal 

Sorry for late reply.

I have used this lib for years. I decided to upgrade the version of lib recently. Here is my code for using this lib. [Source](https://github.com/npes87184/S2TDroid/blob/pro/app/src/main/java/com/npes87184/s2tdroid/donate/BubbleService.java)

I modified Magnet.Builder to Magnet.newBuilder. And it looks well until I try to remove it...

Thank you for your help.

Sincerely,
YCLin
