### ISSUE TITLE
App crashes on Android Oreo while showing a magnet

### ISSUE THREAD

**Issue by patelnishantk** [premnirmal/Magnet#23]
android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@4bd3454 – permission denied for window type 2006

Happens probably because flag WindowManager.LayoutParams.TYPE_SYSTEM_OVERLAY was deprecated since API level 26. Need to use WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY

https://developer.android.com/about/versions/oreo/android-8.0-changes.html

https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#TYPE_SYSTEM_OVERLAY

**Comment by premnirmal** [comment]
Thanks for reporting the issue. Will fix it soon. If you have a fix for it please file a PR
