### ISSUE TITLE
How to set position for Magnet without the animation?

### ISSUE THREAD

**Issue by SCStudioSummer** [premnirmal/Magnet#28]
Dear Premnirmal,

Thanks for share this great library : )

Since the method "setPosition(x, y, animate)" was deprecated,

is it possible to set position for Magnet without the animation (works like "setPosition(x, y, false)") in this version?

Thank you very much.

Best,

Summer

**Comment by premnirmal** [comment]
If you want to set the position without an animation, you must destroy the magnet and create a new magnet with an initial position

**Comment by SCStudioSummer** [comment]
Thanks for your advice, I will try it :) 
Thank you very much!

**Comment by SCStudioSummer** [comment]
Dear Prem Nirmal,

Sorry to bother you again...

I just found that the animation also happened when create the magnet with an initial position, because the Magnet class seemed processing initial positions with some animation codes(?).

Thanks for your reply and inspiration! :)

Best,

Summer





取得 iOS 版 Outlook<https://aka.ms/o0ukef>
________________________________
