### ISSUE TITLE
How to set start position

### ISSUE THREAD

**Issue by robbysmeticapps** [premnirmal/Magnet#4]
Hi,

I want the magnet to start at the right side of the screen. How can I do this?

**Comment by premnirmal** [comment]
Added an option to the builder so you can set the initial position of the magnet:
`Builder#setInitialPosition(int x, int y)`

Also added a method so you can call `Magnet#setPosition(int x, int y, boolean animate)` anytime after it's shown.

See version 1.1.2

**Comment by premnirmal** [comment]
It'll take some time for the artifact to be uploaded to mavenCentral

**Comment by robbysmeticapps** [comment]
Wow, thanks for the quick fix!
