### ISSUE TITLE
Stick to wall horizontal only

### ISSUE THREAD

**Issue by robbysmeticapps** [premnirmal/Magnet#5]
Hi,

Thanks for the quick fix on the other issue. 
I have another request, I would like the 'Stick to wall' option to only work horizontally, so only stick to the left or right wall.

**Comment by premnirmal** [comment]
You can do this by subclassing `Magnet.java` and overriding this method: https://github.com/premnirmal/Magnet/blob/master/library/src/main/java/com/premnirmal/Magnet/Magnet.java#L262 like so:

``` java
   @Override
   protected void goToWall() {
        if (shouldStickToWall) {
            final float nearestXWall = mLayoutParams.x >= 0 ? mWidth : -mWidth;
            mAnimator.start(nearestXWall, mLayoutParams.y);
         }
    }
```

The above code basically removes the check to see which wall is closest (X or Y), instead always snap to the X wall.

**Comment by premnirmal** [comment]
You will also have to subclass the `Builder` so it instantiates your subclass of `Magnet`

**Comment by robbysmeticapps** [comment]
Hi, I have some problems achieving this. 

I can't access the start method of the MoveAnimator. It says 'start(float, float) has protected access in com.premnirmal.Magnet.Magnet.MoveAnimator. 

Also, the magnet field is not public in the Magnet.Builder so I can't set it to my CustomMagnet.

**Comment by premnirmal** [comment]
Bear with me while I make that class and the `start(float, float)` method public. I'll release 1.1.4 to maven central once it's done.

Thanks for pointing this out

**Comment by premnirmal** [comment]
This is fixed now. Version `1.1.4` has been uploaded to maven central. Give it a few hours to upload.

Once you have `1.1.4` you can Subclass `Magnet` and the `Magnet.Builder`, and use the following for horizontal stick to wall only:

``` java
@Override
   protected void goToWall() {
        if (shouldStickToWall) {
            final float nearestXWall = mLayoutParams.x >= 0 ? mWidth : -mWidth;
            mAnimator.start(nearestXWall, mLayoutParams.y);
         }
    }
```

**Comment by robbysmeticapps** [comment]
It works now, I can access the animator. 

One more issue, 
I've subclassed the Magnet.Builder but I can't access the magnet field. 
Could you make that public so I can override it? 

Thanks!

**Comment by premnirmal** [comment]
Updated. You can instantiate your subclass like this:

``` java
final MyMagnet magnet = (MyMagnet) new Builder(MyMagnet.class, context)
                        .setIconView(iconView)
                        .build();
```

Version `1.1.5` is released to maven central. Give it a few hours to go through.

**Comment by robbysmeticapps** [comment]
Thanks, it works now!
