### ISSUE TITLE
uses-sdk element cannot have a "tools:node" attribute

### ISSUE THREAD

**Issue by jd-alexander** [premnirmal/Magnet#8]
When I try to add this library to my app I get this error.

>Error:Execution failed for task ':hover:processDebugAndroidTestManifest'.
  java.lang.RuntimeException: Manifest merger failed : uses-sdk element cannot have a "tools:node" attribute

**Comment by premnirmal** [comment]
Fixed - published `1.1.3` to maven central. Give it a few hours to upload

**Comment by jd-alexander** [comment]
Ok thanks!
